server:
  port: 8080
  servlet:
      context-path: /lo
  tomcat:
    max-threads: 1
    max-connections: 2

spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://mall1:33060/test
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        mode: HTML5
        content-type: text/html