### get
GET {{baseUrl}}/getPort


### post
POST {{baseUrl}}/post
Content-Type: application/json

{
  "bodyParam":"test"
}

### post xml
POST {{baseUrl}}/post/xml
Content-Type: application/xml

<Users>
<id>449</id>
<name>aaa</name>
</Users>
### post xml
POST {{baseUrl}}/post/xml
Content-Type: application/json

{
  "id":"449",
  "name": "aa"
}



### postWithUrlParam
POST {{baseUrl}}/postWithUrlParam
Content-Type: application/json

{
  "bodyParam":"test"
}

### get
GET {{baseUrl}}/user/insert
Accept: */*
Cache-Control: no-cache

###

